# Generated by Django 4.1.3 on 2023-04-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12500)),
                ('sysptoms', models.CharField(max_length=12500)),
                ('Desc', models.CharField(max_length=12500)),
                ('commonTestsAndProceduresDesc', models.CharField(max_length=12500)),
                ('commonTestsAndProcedures', models.CharField(max_length=12500)),
                ('commonMedicationsDesc', models.CharField(max_length=12500)),
                ('commonMedications', models.CharField(max_length=12500)),
                ('whoIsAtRiskDesc', models.CharField(max_length=12500)),
                ('symptomsDesc', models.CharField(max_length=12500)),
            ],
        ),
    ]
